### ISSUE TITLE
Consumo de Folios, RangoUtilizados no considera saltos de secuencias en folios

### ISSUE THREAD

**Issue by celm1990** [dansanti/l10n_cl_libro_compra_venta#1]
En un entorno multi tiendas puedo configurar un rango de folios para cada tienda, ejemplo:
Tienda     Rango de Folio
A                1-500
B           501-1000
C         1001-1500
D         1501-2000

Cuando se hacen ventas y el consumo de folios fue de la siguiente manera:

Tienda     Rango usado
A                1-100
B            501-600
C          1001-1100
D          1501-1600

Al generar el consumo de folios, espera que todo vaya en secuencia y me genera un solo elemento xml RangoUtilizados del 1 al 1600 lo cual es erroneo. 
&lt;RangoUtilizados&gt;
    &lt;desde&gt;1&lt;/desde&gt;
    &lt;hasta&gt;1600&lt;/hasta&gt;
&lt;/RangoUtilizados&gt;

**# Lo correcto seria:**

&lt;RangoUtilizados>
    &lt;desde&gt;1&lt;/desde&gt;
    &lt;hasta&gt;100&lt;/hasta&gt;
&lt;/RangoUtilizados&gt;

&lt;RangoUtilizados&gt;
    &lt;desde&gt;501&lt;/desde&gt;
    &lt;hasta&gt;600&lt;/hasta&gt;
&lt;/RangoUtilizados&gt;

&lt;RangoUtilizados&gt;
    &lt;desde&gt;1001&lt;/desde&gt;
    &lt;hasta&gt;1100&lt;/hasta&gt;
&lt;/RangoUtilizados&gt;

&lt;RangoUtilizados&gt;
    &lt;desde&gt;1501&lt;/desde&gt;
    &lt;hasta&gt;1600&lt;/hasta&gt;
&lt;/RangoUtilizados&gt;

El problema esta en que nunca es llamada  [esta funcion](https://github.com/dansanti/l10n_cl_libro_compra_venta/blob/9.0/models/consumo_folios.py#L703)

y siempre se usa el primer elemento [aqui](https://github.com/dansanti/l10n_cl_libro_compra_venta/blob/9.0/models/consumo_folios.py#L701)

Este [commit](https://github.com/dansanti/l10n_cl_libro_compra_venta/commit/35ae05c1653863e5176443577afd159f0ddf7b3b#diff-d800d1134c642197a4d5e24fdc986fab) intenta reparar eso pero faltaria algo en el algoritmo aun....

Podemos mejorar ese algoritmo???

**Comment by dansanti** [comment]
En la noche subiré subiré cambios, relativos a eso

El 19/01/2017 18:24, "Carlos Lopez" <notifications@github.com> escribió:

En un entorno multi tiendas puedo configurar un rango de folios para cada
tienda, ejemplo:
Tienda Rango de Folio
A 1-500
B 501-1000
C 1001-1500
D 1501-2000

Cuando se hacen ventas y el consumo de folios fue de la siguiente manera:

Tienda Rango usado
A 1-100
B 501-600
C 1001-1100
D 1501-1600

Al generar el consumo de folios, espera que todo vaya en secuencia y me
genera un solo elemento xml RangoUtilizados del 1 al 1600 lo cual es
erroneo.
<RangoUtilizados>
<desde>1</desde>
<hasta>1600</hasta>
</RangoUtilizados>

*# Lo correcto seria:*

<RangoUtilizados>
<desde>1</desde>
<hasta>100</hasta>
</RangoUtilizados>

<RangoUtilizados>
<desde>501</desde>
<hasta>600</hasta>
</RangoUtilizados>

<RangoUtilizados>
<desde>1001</desde>
<hasta>1100</hasta>
</RangoUtilizados>

<RangoUtilizados>
<desde>1501</desde>
<hasta>1600</hasta>
</RangoUtilizados>

El problema esta en que nunca es llamada esta funcion
<https://github.com/dansanti/l10n_cl_libro_compra_venta/blob/9.0/models/consumo_folios.py#L703>

y siempre se usa el primer elemento aqui
<https://github.com/dansanti/l10n_cl_libro_compra_venta/blob/9.0/models/consumo_folios.py#L701>

Este commit
<https://github.com/dansanti/l10n_cl_libro_compra_venta/commit/35ae05c1653863e5176443577afd159f0ddf7b3b#diff-d800d1134c642197a4d5e24fdc986fab>
intenta reparar eso pero faltaria algo en el algoritmo aun....

Podemos mejorar ese algoritmo???

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dansanti/l10n_cl_libro_compra_venta/issues/1>, or mute
the thread
